# Generated by Django 3.2.25 on 2024-05-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytaskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'verbose_name_plural': 'TaskAssignments'},
        ),
    ]
